import type { Product } from "./types"

export const sampleCatalogProducts: Product[] = [
  {
    id: "cat-1",
    name: "Premium Jasmine Rice 25kg",
    price: 32,
    category: "Rice & Grains",
    description:
      "Export-grade jasmine rice selected for importers, distributors, and specialty grocery channels supplying China. Available in retail and wholesale bag formats.",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=80",
    type: "catalog",
    specifications: {
      Origin: "Thailand / Vietnam",
      Packaging: "5kg, 10kg, 25kg bags",
      Moisture: "Max 14%",
      Broken: "Max 5%",
      Container: "20ft / 40ft",
      ShelfLife: "24 months",
      Program: "Private label available",
    },
    createdAt: "2024-01-15",
  },
  {
    id: "cat-2",
    name: "Canned Sweet Corn 425g",
    price: 14,
    category: "Canned Goods",
    description:
      "Whole kernel sweet corn packed for retail, wholesale, and food service buyers. Produced with export labeling support and mixed container compatibility.",
    image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=1200&q=80",
    type: "catalog",
    specifications: {
      Origin: "China / Thailand",
      Packaging: "24 cans per carton",
      Ingredients: "Corn, water, salt",
      NetWeight: "425g",
      ShelfLife: "36 months",
      Container: "Mixed dry container",
      Program: "Retail and food service",
    },
    createdAt: "2024-01-20",
  },
  {
    id: "cat-3",
    name: "Natural Coconut Water 330ml",
    price: 11,
    category: "Beverages",
    description:
      "Shelf-stable coconut water for modern grocery, convenience, and health-focused channels. Offered in branded or private label export programs.",
    image: "/images/products/natural-coconut-water-330ml.png",
    type: "catalog",
    specifications: {
      Origin: "Vietnam / Thailand",
      Packaging: "24 bottles per tray",
      Volume: "330ml",
      ShelfLife: "12 months",
      Container: "Dry container",
      Certification: "HACCP / ISO",
      Program: "Retail and e-commerce",
    },
    createdAt: "2024-02-01",
  },
  {
    id: "cat-4",
    name: "Frozen Mixed Vegetables 1kg",
    price: 9,
    category: "Frozen Foods",
    description:
      "Frozen export product prepared for food service, wholesale, and supermarket programs requiring stable cold-chain coordination.",
    image: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1200&q=80",
    type: "catalog",
    specifications: {
      Origin: "China",
      Packaging: "10 bags per master carton",
      Temperature: "-18C",
      ShelfLife: "24 months",
      Container: "Reefer container",
      Certification: "BRC / HACCP",
      Program: "Food service and retail",
    },
    createdAt: "2024-02-10",
  },
  {
    id: "cat-5",
    name: "Garlic Chili Sauce 500ml",
    price: 16,
    category: "Spices & Seasonings",
    description:
      "High-rotation condiment developed for distributors, restaurants, and specialty grocery formats. Offered in export cartons and private label options.",
    image: "/images/products/garlic-chili-sauce-500ml.png",
    type: "catalog",
    specifications: {
      Origin: "Thailand",
      Packaging: "12 bottles per carton",
      Flavor: "Medium heat",
      Volume: "500ml",
      ShelfLife: "18 months",
      Container: "Dry container",
      Program: "Food service and retail",
    },
    createdAt: "2024-02-15",
  },
  {
    id: "cat-6",
    name: "Mixed Food Container Program",
    price: 0,
    category: "Container Programs",
    description:
      "Consolidated export program that combines dry goods, sauces, canned foods, and beverages into one commercial shipment based on your buying plan.",
    image: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&w=1200&q=80",
    type: "catalog",
    specifications: {
      Format: "FCL / LCL",
      Products: "Mixed dry or reefer options",
      Support: "Documentation and packing list",
      Loading: "Container planning support",
      Labeling: "Retail and wholesale formats",
      Market: "China-focused retail and wholesale programs",
      Program: "Recurring or seasonal",
    },
    createdAt: "2024-03-01",
  },
]

export const sampleStoreProducts: Product[] = [
  {
    id: "store-1",
    name: "Basmati Rice Retail Pack",
    price: 21.99,
    category: "Rice & Grains",
    description:
      "Retail-ready basmati rice pack suitable for ethnic grocery, wholesale club, and supermarket distribution channels.",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1200&q=80",
    type: "store",
    createdAt: "2024-01-10",
  },
  {
    id: "store-2",
    name: "Sparkling Fruit Beverage",
    price: 18.5,
    category: "Beverages",
    description:
      "Fruit beverage export program with colorful retail presentation and scalable private label capabilities.",
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=1200&q=80",
    type: "store",
    createdAt: "2024-01-18",
  },
  {
    id: "store-3",
    name: "Canned Tuna in Oil",
    price: 23.0,
    category: "Canned Goods",
    description:
      "Export-grade canned tuna packed for food service, wholesale, and supermarket programs with long shelf life and stable carton configuration.",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=1200&q=80",
    type: "store",
    createdAt: "2024-02-05",
  },
  {
    id: "store-4",
    name: "Fresh Avocado Program",
    price: 0,
    category: "Fresh Produce",
    description:
      "Commercial avocado supply for importers and produce buyers requiring seasonal planning, spec alignment, and cold-chain coordination.",
    image: "https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?auto=format&fit=crop&w=1200&q=80",
    type: "store",
    createdAt: "2024-02-12",
  },
  {
    id: "store-5",
    name: "Ground Turmeric 25kg",
    price: 48.99,
    category: "Spices & Seasonings",
    description:
      "Bulk turmeric powder with consistent mesh, moisture control, and export documentation for processors and food distributors.",
    image: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?auto=format&fit=crop&w=1200&q=80",
    type: "store",
    createdAt: "2024-02-20",
  },
  {
    id: "store-6",
    name: "Mixed Retail Container",
    price: 0,
    category: "Container Programs",
    description:
      "Commercial container proposal combining high-rotation food categories for importers looking to optimize freight and assortment mix.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1200&q=80",
    type: "store",
    createdAt: "2024-03-05",
  },
]
